### ISSUE TITLE
Text broken in non-English client

### ISSUE THREAD

**Issue by comiluv** [Larsj02/Remix-Gem-Helper#3]
![WoWScrnShot_051824_071021](https://github.com/Larsj02/Remix-Gem-Helper/assets/19642705/812e57a3-d5be-4f07-be09-32241330a4e3)

The addon seems to refer to a font called "expressway.ttf" but this font doesn't seem to support languages other than English

**Comment by Larsj02** [comment]
Which Language is that ?

**Comment by Larsj02** [comment]
Fixed this in the newest Commit (next Release after 1.2.2)

**Comment by comiluv** [comment]
Issue persists in 1.3.0
Locale is koKR
![WoWScrnShot_051924_070900](https://github.com/Larsj02/Remix-Gem-Helper/assets/19642705/33b765b4-d054-4850-93b1-2de84ee7c2ca)
